title: CSC2E01
tagline: CSC2E01 - Artificial Intelligence 
description: Artificial Intelligence 
author: Anoop Kadan, Manjary P. Gangan
exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
markdown: kramdown

# Theme settings
remote_theme: pmarsceill/just-the-docs@v0.3.3
color_scheme: light
search_enabled: true
heading_anchors: true
permalink: pretty
